add to AUR

diff --git a/quand b/quand
--- a/quand
+++ b/quand
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-VERSION="1.0.2"
+VERSION="0.2"
 CONF="${XDG_CONFIG_HOME:-$HOME/.config}/quand/config"
 
 language="${LANG:-en_US.utf-8}"
@@ -69,9 +69,8 @@ main() {
 	c|cal)
 		calendar "$2"
 		return ;;
-
 	'')
-		exec 2>/dev/null ;;
+		exec ;;
 	*)
 		printf 'Error: unknown option %s\n' "$*" 1>&2
 		usage
@@ -79,7 +78,7 @@ main() {
 	esac
 
 	[ ! -f "$calendar" ] &&
-		printf 'Error: %s is not a valid file\n' "$calendar" &&
+		printf 'Error: %s is not a valid file\n' "$calendar" 1>&2 &&
 		return 1
 
 	year="$(date "+%Y")" # this is inaccurate
