add help message, simplify settings parsing, make quand more similar to when

diff --git a/quand b/quand
--- a/quand
+++ b/quand
@@ -1,130 +1,97 @@
 #!/bin/sh
 
-VERSION="1.0.1"
+VERSION="1.0.2"
 CONF="${XDG_CONFIG_HOME:-$HOME/.config}/quand/config"
 
 language="${LANG:-en_US.utf-8}"
-calendar="${XDG_CONFIG_HOME:-$HOME/.config}/quand/calendar"
+calendar="${XDG_DATA_HOME:-$HOME/.local/share}/quand/calendar"
 editor="${EDITOR:-vi}"
-header=0
-past=0
-future=1
-yesterday="yesterday"
-today="\033[1mtoday"
-tomorrow="tomorrow"
+header=1
+past=-1
+future=14
+yesterday="yesterday  "
+today="\033[1mtoday      "
+tomorrow="tomorrow   "
 mondayfirst=0
-
-lstrip() {
-	printf '%s\n' "${1##"$2"}"
-}
-
-trimspaces() {
-	set -f
-	old_ifs=$IFS
-	IFS=" "
-	# shellcheck disable=SC2086
-	set -- $1
-	IFS=
-	printf '%s\n' "$*"
-	IFS=$old_ifs
-	set +f
-}
 
 getday() {
 	date --date="$1 day" "+%m %d"
 }
 
 getnameday() {
-	LC_ALL="$language" date --date="$1 day" "+%a"
+	LC_ALL="$language" date --date="$1 day" "+%a        "
 }
 
 print() {
 	while IFS= read -r line || [ -n "$line" ]; do
 		case $line in
 		"$year $1"*|"* $1"*)
-			printf "$2\033[m    %s\n"  "$line" ;;
+			printf "$2\033[m%s\n"  "$line" ;;
 		esac
 	done < "$calendar"
 }
 
 
-printhelp() {
-	printf "read the README\n"
-}
+usage() {
+	printf 'Usage: %s [options]
 
-getsettings() {
-	while IFS= read -r line || [ -n "$line" ]; do
-		case $line in
-		"language"*)
-			language="$(lstrip "$(trimspaces "$line")" "language=")" ;;
-		"calendar"*)
-			calendar="$(lstrip "$(trimspaces "$line")" "calendar=")" ;;
-		"editor"*)
-			editor="$(lstrip "$(trimspaces "$line")" "editor=")" ;;
-		"header"*)
-			header="$(lstrip "$(trimspaces "$line")" "header=")" ;;
-		"future"*)
-			future="$(lstrip "$(trimspaces "$line")" "future=")" ;;
-		"past"*)
-			past="$(lstrip "$(trimspaces "$line")" "past=")" ;;
-		"yesterday"*)
-			yesterday="$(lstrip "$(trimspaces "$line")" "yesterday=")" ;;
-		"today"*)
-			today="$(lstrip "$(trimspaces "$line")" "today=")" ;;
-		"tomorrow"*)
-			tomorrow="$(lstrip "$(trimspaces "$line")" "tomorrow=")" ;;
-		"mondayfirst"*)
-			mondayfirst="$(lstrip "$(trimspaces "$line")" "mondayfirst=")" ;;
-		esac
-	done < "$CONF"
+Options:
+no option             | Default
+                      |
+e|edit                | Edit the calendar file
+c|cal [n]             | Print a calendar with 1 or n months
+                      │
+-h|--help             │ Print this help message and exit
+-v|--version          | Print the version\n' "${0##*/}" 1>&2
 }
 
 calendar() {
 	if [ "$mondayfirst" -eq 1 ]; then
-		LC_ALL="$language" cal -m
+		LC_ALL="$language" cal -m -n "${1:-1}"
 	else
-		LC_ALL="$language" cal -s
+		LC_ALL="$language" cal -s -n "${1:-1}"
 	fi
 }
 
 main() {
-	getsettings
+	[ -f "$CONF" ] && . "$CONF"
 
-	case $* in
+	case $1 in
 	-v|--version)
-		printf '%s %s\n' "${0##*/}" "$VERSION"
+		printf '%s %s\n' "${0##*/}" "$VERSION" 1>&2
 	 	return 0 ;;
 	-h|--help)
-		printhelp
+		usage
 		return 0 ;;
-	e|edit|-e|--edit)
+	e|edit)
 		"$editor" "$calendar"
-		return 0 ;;
-	c|calendar|-c|--calendar)
-		calendar
-		return 0 ;;
+		return ;;
+	c|cal)
+		calendar "$2"
+		return ;;
+
 	'')
 		exec 2>/dev/null ;;
 	*)
-		printf 'Error: unknown option %s\n' "$*"
-		printhelp
+		printf 'Error: unknown option %s\n' "$*" 1>&2
+		usage
 		return 1 ;;
 	esac
 
 	[ ! -f "$calendar" ] &&
-		printf '%s is not a valid file\n' "$calendar" &&
+		printf 'Error: %s is not a valid file\n' "$calendar" &&
 		return 1
 
 	year="$(date "+%Y")" # this is inaccurate
 
 	[ "$header" = 1 ] && printf '%s\n\n' "$(LC_ALL="$language" date)"
 
-	while [ "$past" -gt 1 ]; do
-		print "$(getday "-$past")" "$(getnameday "-$past")"
-		past=$((past-1))
+	while [ "$past" -lt -1 ]; do
+		print "$(getday "$past")" "$(getnameday "$past")"
+		past=$((past+1))
 	done
 
-	[ "$past" -eq 1 ] && print "$(getday "-1")" "$yesterday"
+	[ "$past" -eq -1 ] && print "$(getday "-1")" "$yesterday"
 
 	print "$(getday 0)" "$today"
 
@@ -141,3 +108,4 @@ main() {
 }
 
 main "$@"
+
