handle multiple args

diff --git a/quand b/quand
--- a/quand
+++ b/quand
@@ -1,6 +1,7 @@
 #!/bin/sh
+# shellcheck disable=SC2046
 
-VERSION="0.3"
+VERSION="0.4"
 CONF="${XDG_CONFIG_HOME:-$HOME/.config}/quand/config"
 
 language="${LANG:-en_US.UTF-8}"
@@ -64,6 +65,35 @@ calendar() {
 	fi
 }
 
+args() {
+	while [ -n "$*" ]; do
+		case $1 in
+		-c|--calendar)
+			[ -z "$2" ] &&
+				printf 'Error: no argument given\n' 1>&2 &&
+				exit 1
+			calendar="$2" ;;
+		-p|--past)
+			[ -z "$2" ] &&
+				printf 'Error: no argument given\n' 1>&2 &&
+				exit 1
+			[ "$2" -gt 0 ] &&
+				printf "\033[33mHint:\033[m 'past' is negative.\n\n"
+			past="$2" ;;
+		-f|--future)
+			[ -z "$2" ] &&
+				printf 'Error: no argument given\n' 1>&2 &&
+				exit 1
+			future="$2" ;;
+		*)
+			printf 'Error: unknown option %s\n' "$*" 1>&2
+			usage
+			exit 1 ;;
+		esac
+		shift 2
+	done
+}
+
 usage() {
 	printf 'Usage: %s [options]
 
@@ -71,6 +101,7 @@ Options:
 no option             | Default
 -h|--help             │ Print this help message and exit
 -v|--version          | Print the version
+-c|--calendar [path]  | Temporarily change the calendar file used
 -p|--past [n]         | Temporarily change past (n is negative)
 -f|--future [n]       | Temporarily change future (n is positive)
                       |
@@ -87,7 +118,7 @@ main() {
 	case $1 in
 	-v|--version)
 		printf '%s %s\n' "${0##*/}" "$VERSION" 1>&2
-	 	return 0 ;;
+		return 0 ;;
 	-h|--help)
 		usage
 		return 0 ;;
@@ -97,17 +128,8 @@ main() {
 	c|cal)
 		calendar "$2"
 		return ;;
-	-p|--past)
-		[ -z "$2" ] &&
-			printf 'Error: no argument given\n' 1>&2 &&
-			return 1
-		past="$2"
-		exec ;;
-	-f|--future)
-		[ -z "$2" ] &&
-			printf 'Error: no argument given\n' 1>&2 &&
-			return 1
-		future="$2"
+	-*)
+		args "$@"
 		exec ;;
 	'')
 		exec ;;
@@ -127,23 +149,18 @@ main() {
 	[ "$header" = 1 ] && printf '%s\n\n' "$(LC_ALL="$language" date)"
 
 	while [ "$past" -lt -1 ]; do
-		# shellcheck disable=SC2046
 		print $(split "$(getdate "$past")")
 		past=$((past+1))
 	done
 
-	# shellcheck disable=SC2046
 	[ "$past" -eq -1 ] && print $(split "$(getdate "-1")") "$yesterday"
 
-	# shellcheck disable=SC2046
 	print $(split "$(getdate 0)") "$today"
 
-	# shellcheck disable=SC2046
 	[ "$future" -ge 1 ] && print $(split "$(getdate "+1")") "$tomorrow"
 
 	cpt=2
 	while [ "$future" -gt 1 ]; do
-		# shellcheck disable=SC2046
 		print $(split "$(getdate "+$cpt")")
 		future="$((future-1))"
 		cpt="$((cpt+1))"
